### PR TITLE
Update handlebars dependency to 2.0.0

### PR DESCRIPTION
**Pull request by roncli**

### CODE REVIEW

**Comment by connor4312** [comment]
This would be great! Though not backwards compatible.

**Comment by roncli** [comment]
Unfortunately not backwards compatible, no.  From https://github.com/wycats/handlebars.js/blob/master/release-notes.md

```
Runtime compatibility breaks in both directions. Ensure that both compiler and client are upgraded to 2.0.0-beta.1 or higher at the same time.
```

I'm currently using handlebars@1.3.0, grunt-contrib-handlebars@0.8.0, and rendr-handlebars@0.2.2.

There is handlebars@2.0.0 and grunt-contrib-handlebars>=0.9.0, but no rendr-handlebars available just yet.

**Comment by saponifi3d** [comment]
This just works? that's pretty exciting.. however the problem is there are so many dependencies in grunt / gulp that depend on 1.3.0 of handlebars. I've been trying to get some other things up-to-date before doing this one.

I think it *might* be problematic for some people that are using other tools with handlebars.  I'll start investigating other grunt / gulp plugins and see if we can get this merged!

**Comment by saponifi3d** [comment]
@roncli i agree this would be super nice, but i keep running into issues with just upgrading handlebars to 2.0.0.  I'm pretty sure it has something to do with the fact i'm using gulp-emblem to turn emblem into handlebars, then using rendr-handlebars. I'll keep investigating to make sure that's the breaking point. 

Sorry for the delay on this PR! Thanks for the contribution!!! PS - Rendr is about to upgrade to 1.0.0, you'll want to upgrade that once it's released. :dancers:

**Comment by roncli** [comment]
I'm starting my rendr 1.0.0 upgrade, and things are going smoothly so far.

handlebars is now two major versions ahead at 3.0.0 now with new breaking API changes between 2.0.0 and 3.0.0.  However, in my limited testing, the same solution applies: package.json just needs to have its reference updated.

grunt-contrib-handlebars is also behind a version, but there is a request out to add handlebars 3.0.0 support at gruntjs/grunt-contrib-handlebars#136.

**Comment by saponifi3d** [comment]
@roncli i agree that we want to upgrade this dependency, for some reason this isn't working for me though (with just an upgrade). I'm investigating it and make sure it's nothing on my end, or what the fixes would be.

**Comment by saponifi3d** [comment]
Running into two issues in a vanilla rendr app with handlebars 2.0.0

```
// Happens on first page load
500 Error: Unknown template object: function
   at new Error (<anonymous>)
   at Error.Exception (/example-app/node_modules/rendr-handlebars/node_modules/handlebars/dist/cjs/handlebars/exception.js:13:41)
   at Object.template (/example-app/node_modules/rendr-handlebars/node_modules/handlebars/dist/cjs/handlebars/runtime.js:34:11)
   at HandlebarsEnvironment.hb.template (/example-app/node_modules/rendr-handlebars/node_modules/handlebars/dist/cjs/handlebars.runtime.js:24:20)
   at Object.module.exports [as /example-app/app/templates/compiledTemplates] (/example-app/app/templates/compiledTemplates.js:5:38)
   at Object.getTemplate (/example-app/node_modules/rendr-handlebars/shared/templateFinder.js:35:52)
   at module.exports.Backbone.View.extend.getTemplate (/example-app/node_modules/rendr/shared/base/view.js:131:37)
   at module.exports.Backbone.View.extend.getInnerHtml (/example-app/node_modules/rendr/shared/base/view.js:182:25)
   at module.exports.Backbone.View.extend.getHtml (/example-app/node_modules/rendr/shared/base/view.js:198:21)
   at ViewEngine.getViewHtml (/example-app/node_modules/rendr/server/viewEngine.js:69:15)
```

```
// every subsequent attempt to load the page
500 Error: home/index: template "home/index" not found.
   at module.exports.Backbone.View.extend.getInnerHtml (/example-app/node_modules/rendr/shared/base/view.js:189:13)
   at module.exports.Backbone.View.extend.getHtml (/example-app/node_modules/rendr/shared/base/view.js:198:21)
   at ViewEngine.getViewHtml (/example-app/node_modules/rendr/server/viewEngine.js:69:15)
   at ViewEngine.render (/example-app/node_modules/rendr/server/viewEngine.js:22:16)
   at View.render (/example-app/node_modules/rendr/node_modules/express/lib/view.js:93:8)
   at EventEmitter.app.render (/example-app/node_modules/rendr/node_modules/express/lib/application.js:530:10)
   at ServerResponse.res.render (/example-app/node_modules/express/lib/response.js:938:7)
   at /example-app/node_modules/rendr/server/router.js:87:11
   at Object.module.exports.index (/example-app/app/controllers/home_controller.js:3:5)
   at /example-app/node_modules/rendr/server/router.js:74:12
```

so it def looks like a simple "upgrade handlebars" won't work. I'm going to keep plugging away at this (just really starting to dig into the problem and investigate this as it took me a little to get an empty example application up and running on rendr 1.0.0)

**Comment by roncli** [comment]
Assuming rendrjs/rendr-examples/00_simple, here are all of the changes I make to get to rendr 1.0.0 and be compatible with handlebars 2.0.0:

1) Update the app's dependencies:
* rendr to 1.0.0
* rendr-handlebars to 0.2.4
* grunt-contrib-handlebars to ~0.9.0 - This is needed because this is the earliest version of grunt-contrib-handlebars that supports handlebars 2.0.0 API.
* karma to ~0.12.8 - This is needed due to karma-mocha 0.1.10 requiring karma 0.12.8.  Resolves some weird circular dependency.

2) Edit app/app.js to use initialize instead of postInitialize, this makes the app compatible with rendr 1.0.0.

3) npm install to install the libraries.

Now you have to get rendr-handlebars to use the handlebars 2.0.0 API.

4) In node_modules/rendr-handlebars, update rendr-handlebars's dependencies:
* handlebars to 2.0.0

5) cd node_modules/rendr-handlebars

6) npm update handlebars

Now start the server, everything should work.

7) cd ../..

8) grunt server

9) Navigate to localhost:3030

**Comment by saponifi3d** [comment]
ah - cool, i didn't notice the `grunt-contrib-handlebars` bit. that was the thing not working for me w/ the templateFinder :+1: thanks!

**Comment by saponifi3d** [comment]
argh, for no reason this is saying there is a conflict. i'm going to upgrade underscore as well and merge this - sorry it's all screwy. thanks for the help on this!

I'm working on upgrading all the examples in rendr-examples as we speak.

**Comment by saponifi3d** [comment]
https://github.com/rendrjs/rendr-handlebars/pull/49

**Comment by roncli** [comment]
Awesome, thanks for your work! :)

**Pull request closed without merging**
