### PR TITLE
add forgotten require

### PR DESCRIPTION
**Pull request by wvengen**

### CODE REVIEW

**Comment by por** [comment]
@saponifi3d can you have a look at this PR?

**Comment by saponifi3d** [comment]
d'oh, my bad. i'll add some tests around the `view` helper today.

**Comment by por** [comment]
Thanks :beers:

**Comment by saponifi3d** [comment]
@por also merged a basic test that will at least catch this type of thing in the future too. the way it is setup to grab so much from rendr is pretty hard to test... i'm working on rendr documentation right now, then i'll hop back onto testing this using `proxyquire`

**Pull request merged**
